Ejecute mkdir -p ~/.ssh 
  mkdir -p ~/.ssh
  eco "***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  " > ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa
  ssh-keyscan -H *** >> ~/.ssh/known_hosts
  shell: /usr/bin/bash -e {0}
  Env: 
    SERVICE_NAME: paquetes
    SERVICE_PORT: 8081
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.8-9/x64
    JAVA_HOME_21_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.8-9/x64
Error: Proceso completado con el código de salida 1. 
