name: Deploy Paquetes Service

on:
  push:
    branches: [ main ]

env:
  SERVICE_NAME: "paquetes"
  SERVICE_PORT: "8081"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_DNS }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection to ${{ secrets.EC2_DNS }}..."
          ssh -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              -o ConnectTimeout=10 \
              ec2-user@${{ secrets.EC2_DNS }} "echo '✅ SSH connection successful'"

      - name: Deploy Application
        run: |
          # Upload JAR
          scp -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              target/*.jar \
              ec2-user@${{ secrets.EC2_DNS }}:/home/ec2-user/$SERVICE_NAME/
          
          # Deploy
          ssh -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              ec2-user@${{ secrets.EC2_DNS }} "
            cd /home/ec2-user/$SERVICE_NAME
            pkill -f java || true
            sleep 5
            nohup java -jar *.jar --server.port=$SERVICE_PORT --server.address=0.0.0.0 > app.log 2>&1 &
            sleep 30
            if ss -tuln | grep -q ':$SERVICE_PORT'; then
              echo '✅ Deployment successful'
            else
              echo '❌ Deployment failed'
              exit 1
            fi
          "
