name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: Build & Push Docker image
        env:
          IMAGE: ghcr.io/${{ github.repository_owner }}/paquetes
          TAG: ${{ github.sha }}
        run: |
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

      - name: Notify infra repo (optional)
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_FOR_REPO_DISPATCH }}
          repository: "diegoosoriob/infra"
          event-type: "microservice-updated"
          client-payload: '{"service":"paquetes","tag":"${{ github.sha }}"}'
